# 1.Arrays



In [2]:
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    arr1 = numpy.array(arr,float)
    return arr1[::-1]

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


# 2. Shape and Reshape

In [3]:
import numpy
arr = input().strip().split(' ');
arr = numpy.array(arr,int)
print(numpy.reshape(arr,(3,3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 3.Transpose and Flatten



In [4]:
import numpy
n,m = map(int,input().split())
arr = numpy.array([input().strip().split() for i in range(n)],int)

print(numpy.transpose(arr))
print(arr.flatten())

2 3
2 3 4
1 2 3
[[2 1]
 [3 2]
 [4 3]]
[2 3 4 1 2 3]


# 4.Concatenate

In [6]:
import numpy
N,m,p = map(int,input().split())
arr1 = numpy.array([input().strip().split() for i in range(N)],int)
arr2 = numpy.array([input().strip().split() for j in range(m)],int)

print(numpy.concatenate((arr1,arr2)))


2 2 2
1 2
2 3
1 2
3 4
[[1 2]
 [2 3]
 [1 2]
 [3 4]]


# 5.Zeros and Ones

In [8]:
import numpy
lst = tuple(map(int,input().strip().split()))
print (numpy.zeros(lst,dtype = numpy.int),numpy.ones(lst,dtype = numpy.int),sep="\n")

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


# 6.Eye and Identity



In [9]:
import numpy
numpy.set_printoptions(legacy='1.13')
m,n = map(int,input().split())
print(numpy.eye(m,n))


3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


# 7.Array Mathematics



In [10]:
import numpy
m,n = map(int,input().strip().split())
A= numpy.array([input().strip().split() for i in range(m)],int)
B=  numpy.array([input().strip().split() for j in range(m)],int)
print(numpy.add(A, B))
print(numpy.subtract(A, B))
print(numpy.multiply(A, B))
print(numpy.floor_divide(A, B))
print(numpy.mod(A, B))
print(numpy.power(A, B))


1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


# 8.Floor, Ceil and Rint

In [11]:
import numpy
numpy.set_printoptions(legacy='1.13')
arr = numpy.array(input().strip().split(),float)
print(numpy.floor(arr))
print(numpy.ceil(arr))
print(numpy.rint(arr))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


# 9.Sum and Prod

In [12]:
import numpy
n,m= map(int,input().strip().split())
arr = numpy.array([input().split() for i in range(n)],int)
print(numpy.product(numpy.sum(arr,axis=0)))


2 2
2 3
4 5
48


# 10.Min and Max

In [13]:
import numpy
n,m= map(int,input().strip().split())
arr = numpy.array([input().split() for i in range(n)],int)
print(numpy.max(numpy.min(arr,axis=1)))

2 2
1 2
2 3
2


# 11.Mean, Var, and Std

In [14]:
import numpy
n,m= map(int,input().strip().split())
arr = numpy.array([input().split() for i in range(n)],int)
print(numpy.mean(arr,axis=1))
print(numpy.var(arr,axis=0))
print(round(numpy.std(arr,axis=None),11))



2 2
1 2
2 3
[ 1.5  2.5]
[ 0.25  0.25]
0.70710678119


# 12.Dot and Cross

In [16]:
import numpy
n = int(input())
arr = numpy.array([input().split() for i in range(n)],int)
arr1 = numpy.array([input().split() for j in range(n)],int)
print(numpy.matmul(arr,arr1))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


 # 13.Inner and Outer



In [17]:
import numpy
arr = numpy.array([input().split()],int)
arr1 = numpy.array([input().split()],int)
print(numpy.inner(arr,arr1)[0][0])
print(numpy.outer(arr,arr1))

1 2
3 4
11
[[3 4]
 [6 8]]


# 14.Polynomials

In [18]:
import numpy
lst = list(map(float,input().split()))
x = int(input())
print(numpy.polyval(lst,x))




1 2
0
2.0


# 15.Linear Algebra

In [19]:
import numpy
n = int(input())
arr = numpy.array([input().split() for i in range(n)],float)
print (numpy.round(numpy.linalg.det(arr),2)) 

2
1.1 1.1
1.1 1.2
0.11
